/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TableColumnInterface, TableDataInterface, TableRowInterface } from "./components/table/table.interface";
export namespace Components {
    interface SiteRoot {
    }
    interface VudoTable {
        "currentPage": number;
        "data": TableDataInterface;
        "itemsPerPage": number;
    }
}
declare global {
    interface HTMLSiteRootElement extends Components.SiteRoot, HTMLStencilElement {
    }
    var HTMLSiteRootElement: {
        prototype: HTMLSiteRootElement;
        new (): HTMLSiteRootElement;
    };
    interface HTMLVudoTableElement extends Components.VudoTable, HTMLStencilElement {
    }
    var HTMLVudoTableElement: {
        prototype: HTMLVudoTableElement;
        new (): HTMLVudoTableElement;
    };
    interface HTMLElementTagNameMap {
        "site-root": HTMLSiteRootElement;
        "vudo-table": HTMLVudoTableElement;
    }
}
declare namespace LocalJSX {
    interface SiteRoot {
    }
    interface VudoTable {
        "currentPage"?: number;
        "data"?: TableDataInterface;
        "itemsPerPage"?: number;
        "onSearchTable"?: (event: CustomEvent<TableRowInterface[]>) => void;
        "onSortTable"?: (event: CustomEvent<TableColumnInterface>) => void;
    }
    interface IntrinsicElements {
        "site-root": SiteRoot;
        "vudo-table": VudoTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "site-root": LocalJSX.SiteRoot & JSXBase.HTMLAttributes<HTMLSiteRootElement>;
            "vudo-table": LocalJSX.VudoTable & JSXBase.HTMLAttributes<HTMLVudoTableElement>;
        }
    }
}
