/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TableDataInterface } from "./table.interface";
export namespace Components {
    interface VudoTable {
        "data": TableDataInterface;
    }
}
declare global {
    interface HTMLVudoTableElement extends Components.VudoTable, HTMLStencilElement {
    }
    var HTMLVudoTableElement: {
        prototype: HTMLVudoTableElement;
        new (): HTMLVudoTableElement;
    };
    interface HTMLElementTagNameMap {
        "vudo-table": HTMLVudoTableElement;
    }
}
declare namespace LocalJSX {
    interface VudoTable {
        "data"?: TableDataInterface;
    }
    interface IntrinsicElements {
        "vudo-table": VudoTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vudo-table": LocalJSX.VudoTable & JSXBase.HTMLAttributes<HTMLVudoTableElement>;
        }
    }
}
