/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TableDataInterface, } from "./table.interface";
export namespace Components {
    interface IcOn {
        "icon": string;
    }
    interface TaBle {
        "data": TableDataInterface;
    }
}
declare global {
    interface HTMLIcOnElement extends Components.IcOn, HTMLStencilElement {
    }
    var HTMLIcOnElement: {
        prototype: HTMLIcOnElement;
        new (): HTMLIcOnElement;
    };
    interface HTMLTaBleElement extends Components.TaBle, HTMLStencilElement {
    }
    var HTMLTaBleElement: {
        prototype: HTMLTaBleElement;
        new (): HTMLTaBleElement;
    };
    interface HTMLElementTagNameMap {
        "ic-on": HTMLIcOnElement;
        "ta-ble": HTMLTaBleElement;
    }
}
declare namespace LocalJSX {
    interface IcOn {
        "icon"?: string;
    }
    interface TaBle {
        "data"?: TableDataInterface;
    }
    interface IntrinsicElements {
        "ic-on": IcOn;
        "ta-ble": TaBle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ic-on": LocalJSX.IcOn & JSXBase.HTMLAttributes<HTMLIcOnElement>;
            "ta-ble": LocalJSX.TaBle & JSXBase.HTMLAttributes<HTMLTaBleElement>;
        }
    }
}
